// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokedexV.Data;

namespace PokedexV.Migrations
{
    [DbContext(typeof(PokedexVContext))]
    [Migration("20201118211533_InitialTrainersAndCaughtPks")]
    partial class InitialTrainersAndCaughtPks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PokedexV.Models.CaughtPk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaughtDexNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaughtName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("CaughtPk");
                });

            modelBuilder.Entity("PokedexV.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaughtPkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evolve")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaughtPkId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokedexV.Models.TrainerStuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badges")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainerStuff");
                });

            modelBuilder.Entity("PokedexV.Models.CaughtPk", b =>
                {
                    b.HasOne("PokedexV.Models.TrainerStuff", "Trainer")
                        .WithMany("Pokemans")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokedexV.Models.Pokemon", b =>
                {
                    b.HasOne("PokedexV.Models.CaughtPk", null)
                        .WithMany("Pokemins")
                        .HasForeignKey("CaughtPkId");
                });

            modelBuilder.Entity("PokedexV.Models.CaughtPk", b =>
                {
                    b.Navigation("Pokemins");
                });

            modelBuilder.Entity("PokedexV.Models.TrainerStuff", b =>
                {
                    b.Navigation("Pokemans");
                });
#pragma warning restore 612, 618
        }
    }
}
